//
// Created by Artur on 7.10.2025.
//

#ifndef NOTSIMPLEGAME_PLAYERCHANGESTATSDEBUGWINDOW_H
#define NOTSIMPLEGAME_PLAYERCHANGESTATSDEBUGWINDOW_H


class playerChangeStatsDebugWindow {
};


#endif //NOTSIMPLEGAME_PLAYERCHANGESTATSDEBUGWINDOW_H